<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Qr code is already checked by this group.' => '',
    'Question name already exists for this route section' => '',
    'This group already answered this question' => '',
    'This group already checked in on this station.' => '',
    'This hint is already opened by this group.' => '',
    'This hint name alrady exists for this Hike' => '',
    'This qr code exists for this hike' => '',
    'This station name exist for this day.' => '',
    'You cannot remove this hike' => '',
    'You cannot remove this user.' => '',
];
